### ISSUE TITLE
S3-auth not working with Munki 4 Release Candidate 1

### ISSUE THREAD

**Issue by aysiu** [waderobson/s3-auth#12]
Even though I'm seeing commits for Python 3 compatibility, it seems to just bunk out. Anything obvious I'm missing?
```
sudo managedsoftwareupdate -vvv
Password:
Managed Software Update Tool
Copyright 2010-2019 The Munki Project
https://github.com/munki/munki

Starting...
    No CA cert info provided, so nothing to add to System keychain.
    No client cert info provided, so no client keychain will be created.
Checking for available updates...
    No client id specified. Requesting SERIAL...
    Manifest base URL is: https://URLDETAILS/munki_repo/manifests/
    Getting manifest SERIAL...
    Options: {'url': 'https://URLDETAILS/munki_repo/manifests/SERIAL', 'file': '/Library/Managed Installs/manifests/SERIAL.download', 'follow_redirects': 'none', 'ignore_system_proxy': False, 'can_resume': False, 'additional_headers': {'User-Agent': 'managedsoftwareupdate/4.0.0.3881 Darwin/19.0.0'}, 'download_only_if_changed': True, 'cache_data': {
    etag = "\"2171375bed808ff2289b6e8e2f3178de\"";
    "last-modified" = "Fri, 06 Dec 2019 20:55:21 GMT";
}, 'logging_function': <function display_debug2 at 0x112d06f80>}
    Processing options through middleware
ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1141, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 862, in main
    client_id=unicode_or_str(options.id))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 82, in check
    mainmanifestpath = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 175, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 122, in get_manifest
    manifesturl, manifestpath, message=message)
  File "/usr/local/munki/munkilib/fetch.py", line 440, in munki_resource
    verify=verify)
  File "/usr/local/munki/munkilib/fetch.py", line 393, in getResourceIfChangedAtomically
    message=message, resume=resume, follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 525, in getHTTPfileIfChangedAtomically
    follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 246, in get_url
    options = middleware.process_request_options(options)
  File "/usr/local/munki/middleware_s3.py", line 117, in process_request_options
    headers = s3_auth_headers(options['url'])
  File "/usr/local/munki/middleware_s3.py", line 97, in s3_auth_headers
    signing_key = get_signature_key(SECRET_KEY, datestamp, REGION, SERVICE)
  File "/usr/local/munki/middleware_s3.py", line 49, in get_signature_key
    kdate = sign(('AWS4' + key).encode('utf-8'), datestamp)
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by aysiu** [comment]
User error. Had prefs written to `com.github.waderobson.s3-auth` (which used to work) instead of to `ManagedInstalls`.
