### ISSUE TITLE
Error running with munki4

### ISSUE THREAD

**Issue by weiminm** [waderobson/s3-auth#13]
Hi,

I am getting this error running the middleware with munki4.

<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature.</Message>

I get error with munki3 as well.

ERROR: Unexpected error in updatecheck:
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 1140, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 861, in main
    client_id=options.id.decode('UTF-8'))
  File "/usr/local/munki/munkilib/updatecheck/core.py", line 81, in check
    mainmanifestpath = manifestutils.get_primary_manifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 166, in get_primary_manifest
    manifest = get_manifest(clientidentifier, suppress_errors=True)
  File "/usr/local/munki/munkilib/updatecheck/manifestutils.py", line 114, in get_manifest
    manifesturl, manifestpath, message=message)
  File "/usr/local/munki/munkilib/fetch.py", line 428, in munki_resource
    verify=verify)
  File "/usr/local/munki/munkilib/fetch.py", line 381, in getResourceIfChangedAtomically
    message=message, resume=resume, follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 513, in getHTTPfileIfChangedAtomically
    follow_redirects=follow_redirects)
  File "/usr/local/munki/munkilib/fetch.py", line 235, in get_url
    options = middleware.process_request_options(options)
  File "/usr/local/munki/middleware_s3.py", line 117, in process_request_options
    headers = s3_auth_headers(options['url'])
  File "/usr/local/munki/middleware_s3.py", line 90, in s3_auth_headers
    credential_scope = '{}/{}/{}/aws4_request'.format(datestamp, REGION, SERVICE)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 0: ordinal not in range(128)

**Comment by derekjbernard** [comment]
Is this a copy pulled directly from the master branch per the wiki directions? 
I noticed the master branch has a new change on line 81 and 91 that adds utf-8 encoding explicitly to the payload_hash and hashed_request.
[Diff v2..master](https://github.com/waderobson/s3-auth/compare/v1.2...master#diff-29c5b1120abc11b7b49afe898163afb3) 

You could try using the the "latest" release (1.2 as of this writing) which is working well for me with munki 4.1.2.3939. Version 1.2 is older than what's currently in master, but is the official latest release.
Release 1.2:
[https://github.com/waderobson/s3-auth/releases/tag/v1.2](https://github.com/waderobson/s3-auth/releases/tag/v1.2)

**Comment by derekjbernard** [comment]
Pre-coffee replies can be dangerous, I hadn't noticed the age of this issue. I double checked my current deployment and I am running the 1.3 master branch version. Maybe the advice should be the other way around?

**Comment by waderobson** [comment]
@weiminm are you using the latest version? I apologize for getting back to you 4 months later, were you able to get this working?

**Comment by waderobson** [comment]
assuming that @weiminm  is sorted closing
